### ISSUE TITLE
 Module not found: Error: Can't resolve '../BluzelleESR/build/contracts/BluzelleESR.json' 

### ISSUE THREAD

**Issue by chenmyGitHub** [bluzelle/bluzelle-js#59]
When I follow the document to execute the installer, 
when i exec npx webpack， the system prompts for an error

os：macos10.14
npm:6.4
node:10.16.1

https://docs.bluzelle.com/bluzelle-js/installation
![image](https://user-images.githubusercontent.com/7311356/62036780-0d688b00-b225-11e9-93cf-dfb9c3c8e115.png)

**Comment by MontyThibault** [comment]
Hi, thanks for filing the issue. I've given the documentation some updates. Please try again.
