### ISSUE TITLE
Package Not Installing

### ISSUE THREAD

**Issue by sahityakumarsuman** [bluzelle/bluzelle-js#66]
I am not able to add this package as it giving build failed error

**Comment by nickroeker** [comment]
Hello @sahityakumarsuman,

Could you please provide us some more info? We are having no issues installing the most recent version of `bluzelle-js`.

- Operating System & Version
- `nodejs` version (run `node --version`)
- `npm` version (run `npm --version`)
- Your steps to reproduce the issue
- Error details (`npm` output, console messages, stacktraces, etc.)

**Comment by sahityakumarsuman** [comment]
It was a node version issue, I was trying to install it with version 12.8.1 and switching to version 10.16.3 done the job. Also if any of you guys face error while building packages just give a try by switching to 10.16.3 version. 

Thanks
